# Site settings
title: nonlinear.nyc
email: info@nicholasfrota.com
description: Lorem ipsum dolor sit amet, consectetur adipisicing elit. Laudantium, quo!
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://nonlinear.nyc" # the base hostname & protocol for your site
twitter_username: nonlinear
github_username: nonlinear
paginate: 10
markdown: rdiscount
permalink: pretty
highlighter: pygments

