# Site settings
title: Nicholas Frota
email: info@nicholasfrota.com
description: > # this means to ignore newlines until "baseurl:"
  the anagram of my name is anarchist fool
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.nicholasfrota.com" # the base hostname & protocol for your site
twitter_username: nonlinear
github_username:  nonlinear

# Build settings
markdown: kramdown
