title: nonlinear
email: info@nicholasfrota.com
description: >- # this means to ignore newlines until "baseurl:"
  The anagram of my name is anarchist fool
baseurl: ''
basecolor: '#000000' # for browser settings
url: 'https://www.nonlinear.nyc'
twitter_username: nonlinear
github_username: nonlinear

sass:
  load_paths:
    - _sass
    - node_modules
exclude:
  - node_modules
  - LICENSE
  - Makefile
  - README.md
  - package.json
  - package-lock.json
  - yarn.lock

visible:
  - name: study
    description: notes from meetups, events and tutorials
  - name: project
    description: projects I'm working on
  - name: note
    description: stuff?
  - name: processing
    description: my progress on p5*js
